/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDataVerifier,
  IDataVerifierInterface,
} from "../../contracts/IDataVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "verifyOwnership",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "dataHashes",
            type: "bytes32[]",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType: "struct IDataVerifier.OwnershipProofOutput",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "verifyTransferValidity",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "oldDataHashes",
            type: "bytes32[]",
          },
          {
            internalType: "bytes32[]",
            name: "newDataHashes",
            type: "bytes32[]",
          },
          {
            internalType: "bytes",
            name: "pubKey",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "sealedKey",
            type: "bytes",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType: "struct IDataVerifier.TransferValidityProofOutput",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDataVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IDataVerifierInterface {
    return new Interface(_abi) as IDataVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDataVerifier {
    return new Contract(address, _abi, runner) as unknown as IDataVerifier;
  }
}
