/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Marketplace: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3" as const,
      abi: [] as const, // This will be populated by the generateTsAbis script
    },
    MockSapphire: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as const,
      abi: [] as const, // This will be populated by the generateTsAbis script
    },
  },
  11155111: {
    Marketplace: {
      address: "0x0000000000000000000000000000000000000000" as const,
      abi: [] as const,
    },
  },
  23295: {
    // Oasis Sapphire Testnet
    Marketplace: {
      address: "0x0000000000000000000000000000000000000000" as const,
      abi: [] as const,
    },
  },
  23294: {
    // Oasis Sapphire Mainnet
    Marketplace: {
      address: "0x0000000000000000000000000000000000000000" as const,
      abi: [] as const,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;