/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7857DataVerifier,
  IERC7857DataVerifierInterface,
} from "../../../contracts/interfaces/IERC7857DataVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "verifyOwnership",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "dataHashes",
            type: "bytes32[]",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType: "struct IERC7857DataVerifier.OwnershipProofOutput",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "verifyTransferValidity",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "oldDataHashes",
            type: "bytes32[]",
          },
          {
            internalType: "bytes32[]",
            name: "newDataHashes",
            type: "bytes32[]",
          },
          {
            internalType: "bytes",
            name: "pubKey",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "sealedKey",
            type: "bytes",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType: "struct IERC7857DataVerifier.TransferValidityProofOutput",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC7857DataVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7857DataVerifierInterface {
    return new Interface(_abi) as IERC7857DataVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7857DataVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC7857DataVerifier;
  }
}
