/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ERC7857AIAgentsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeUsage"
      | "authorizedUsersOf"
      | "clone"
      | "dataDescriptionsOf"
      | "dataHashesOf"
      | "mint"
      | "name"
      | "ownerOf"
      | "symbol"
      | "tokenURI"
      | "transfer"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedUsage"
      | "Cloned"
      | "Minted"
      | "PublishedSealedKey"
      | "Transferred"
      | "Updated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeUsage",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedUsersOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clone",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "dataDescriptionsOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dataHashesOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BytesLike[], string[]]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "authorizeUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedUsersOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clone", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dataDescriptionsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataHashesOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace AuthorizedUsageEvent {
  export type InputTuple = [tokenId: BigNumberish, user: AddressLike];
  export type OutputTuple = [tokenId: bigint, user: string];
  export interface OutputObject {
    tokenId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClonedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    newTokenId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    newTokenId: bigint,
    from: string,
    to: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    newTokenId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    creator: AddressLike,
    dataHashes: BytesLike[],
    dataDescriptions: string[]
  ];
  export type OutputTuple = [
    tokenId: bigint,
    creator: string,
    dataHashes: string[],
    dataDescriptions: string[]
  ];
  export interface OutputObject {
    tokenId: bigint;
    creator: string;
    dataHashes: string[];
    dataDescriptions: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublishedSealedKeyEvent {
  export type InputTuple = [
    to: AddressLike,
    tokenId: BigNumberish,
    sealedKey: BytesLike
  ];
  export type OutputTuple = [to: string, tokenId: bigint, sealedKey: string];
  export interface OutputObject {
    to: string;
    tokenId: bigint;
    sealedKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [tokenId: bigint, from: string, to: string];
  export interface OutputObject {
    tokenId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    oldDataHashes: BytesLike[],
    newDataHashes: BytesLike[]
  ];
  export type OutputTuple = [
    tokenId: bigint,
    oldDataHashes: string[],
    newDataHashes: string[]
  ];
  export interface OutputObject {
    tokenId: bigint;
    oldDataHashes: string[];
    newDataHashes: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC7857AIAgents extends BaseContract {
  connect(runner?: ContractRunner | null): ERC7857AIAgents;
  waitForDeployment(): Promise<this>;

  interface: ERC7857AIAgentsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeUsage: TypedContractMethod<
    [tokenId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedUsersOf: TypedContractMethod<
    [tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  clone: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish, proofs: BytesLike[]],
    [bigint],
    "payable"
  >;

  dataDescriptionsOf: TypedContractMethod<
    [tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  dataHashesOf: TypedContractMethod<
    [tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  mint: TypedContractMethod<
    [proofs: BytesLike[], dataDescriptions: string[]],
    [bigint],
    "payable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish, proofs: BytesLike[]],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeUsage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedUsersOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "clone"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish, proofs: BytesLike[]],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "dataDescriptionsOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "dataHashesOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [proofs: BytesLike[], dataDescriptions: string[]],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish, proofs: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AuthorizedUsage"
  ): TypedContractEvent<
    AuthorizedUsageEvent.InputTuple,
    AuthorizedUsageEvent.OutputTuple,
    AuthorizedUsageEvent.OutputObject
  >;
  getEvent(
    key: "Cloned"
  ): TypedContractEvent<
    ClonedEvent.InputTuple,
    ClonedEvent.OutputTuple,
    ClonedEvent.OutputObject
  >;
  getEvent(
    key: "Minted"
  ): TypedContractEvent<
    MintedEvent.InputTuple,
    MintedEvent.OutputTuple,
    MintedEvent.OutputObject
  >;
  getEvent(
    key: "PublishedSealedKey"
  ): TypedContractEvent<
    PublishedSealedKeyEvent.InputTuple,
    PublishedSealedKeyEvent.OutputTuple,
    PublishedSealedKeyEvent.OutputObject
  >;
  getEvent(
    key: "Transferred"
  ): TypedContractEvent<
    TransferredEvent.InputTuple,
    TransferredEvent.OutputTuple,
    TransferredEvent.OutputObject
  >;
  getEvent(
    key: "Updated"
  ): TypedContractEvent<
    UpdatedEvent.InputTuple,
    UpdatedEvent.OutputTuple,
    UpdatedEvent.OutputObject
  >;

  filters: {
    "AuthorizedUsage(uint256,address)": TypedContractEvent<
      AuthorizedUsageEvent.InputTuple,
      AuthorizedUsageEvent.OutputTuple,
      AuthorizedUsageEvent.OutputObject
    >;
    AuthorizedUsage: TypedContractEvent<
      AuthorizedUsageEvent.InputTuple,
      AuthorizedUsageEvent.OutputTuple,
      AuthorizedUsageEvent.OutputObject
    >;

    "Cloned(uint256,uint256,address,address)": TypedContractEvent<
      ClonedEvent.InputTuple,
      ClonedEvent.OutputTuple,
      ClonedEvent.OutputObject
    >;
    Cloned: TypedContractEvent<
      ClonedEvent.InputTuple,
      ClonedEvent.OutputTuple,
      ClonedEvent.OutputObject
    >;

    "Minted(uint256,address,bytes32[],string[])": TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;
    Minted: TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;

    "PublishedSealedKey(address,uint256,bytes)": TypedContractEvent<
      PublishedSealedKeyEvent.InputTuple,
      PublishedSealedKeyEvent.OutputTuple,
      PublishedSealedKeyEvent.OutputObject
    >;
    PublishedSealedKey: TypedContractEvent<
      PublishedSealedKeyEvent.InputTuple,
      PublishedSealedKeyEvent.OutputTuple,
      PublishedSealedKeyEvent.OutputObject
    >;

    "Transferred(uint256,address,address)": TypedContractEvent<
      TransferredEvent.InputTuple,
      TransferredEvent.OutputTuple,
      TransferredEvent.OutputObject
    >;
    Transferred: TypedContractEvent<
      TransferredEvent.InputTuple,
      TransferredEvent.OutputTuple,
      TransferredEvent.OutputObject
    >;

    "Updated(uint256,bytes32[],bytes32[])": TypedContractEvent<
      UpdatedEvent.InputTuple,
      UpdatedEvent.OutputTuple,
      UpdatedEvent.OutputObject
    >;
    Updated: TypedContractEvent<
      UpdatedEvent.InputTuple,
      UpdatedEvent.OutputTuple,
      UpdatedEvent.OutputObject
    >;
  };
}
