/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface MockSapphireInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "APIKeyDecrypted"
      | "APIKeyEncrypted"
      | "ROFLAuthorizationCheck"
      | "ROFLStorageAccessed"
      | "ROFLStorageSet"
  ): EventFragment;
}

export namespace APIKeyDecryptedEvent {
  export type InputTuple = [keyHash: BytesLike, accessor: AddressLike];
  export type OutputTuple = [keyHash: string, accessor: string];
  export interface OutputObject {
    keyHash: string;
    accessor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace APIKeyEncryptedEvent {
  export type InputTuple = [keyHash: BytesLike];
  export type OutputTuple = [keyHash: string];
  export interface OutputObject {
    keyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ROFLAuthorizationCheckEvent {
  export type InputTuple = [origin: AddressLike, authorized: boolean];
  export type OutputTuple = [origin: string, authorized: boolean];
  export interface OutputObject {
    origin: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ROFLStorageAccessedEvent {
  export type InputTuple = [key: BytesLike, accessor: AddressLike];
  export type OutputTuple = [key: string, accessor: string];
  export interface OutputObject {
    key: string;
    accessor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ROFLStorageSetEvent {
  export type InputTuple = [key: BytesLike, dataLength: BigNumberish];
  export type OutputTuple = [key: string, dataLength: bigint];
  export interface OutputObject {
    key: string;
    dataLength: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockSapphire extends BaseContract {
  connect(runner?: ContractRunner | null): MockSapphire;
  waitForDeployment(): Promise<this>;

  interface: MockSapphireInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "APIKeyDecrypted"
  ): TypedContractEvent<
    APIKeyDecryptedEvent.InputTuple,
    APIKeyDecryptedEvent.OutputTuple,
    APIKeyDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "APIKeyEncrypted"
  ): TypedContractEvent<
    APIKeyEncryptedEvent.InputTuple,
    APIKeyEncryptedEvent.OutputTuple,
    APIKeyEncryptedEvent.OutputObject
  >;
  getEvent(
    key: "ROFLAuthorizationCheck"
  ): TypedContractEvent<
    ROFLAuthorizationCheckEvent.InputTuple,
    ROFLAuthorizationCheckEvent.OutputTuple,
    ROFLAuthorizationCheckEvent.OutputObject
  >;
  getEvent(
    key: "ROFLStorageAccessed"
  ): TypedContractEvent<
    ROFLStorageAccessedEvent.InputTuple,
    ROFLStorageAccessedEvent.OutputTuple,
    ROFLStorageAccessedEvent.OutputObject
  >;
  getEvent(
    key: "ROFLStorageSet"
  ): TypedContractEvent<
    ROFLStorageSetEvent.InputTuple,
    ROFLStorageSetEvent.OutputTuple,
    ROFLStorageSetEvent.OutputObject
  >;

  filters: {
    "APIKeyDecrypted(bytes32,address)": TypedContractEvent<
      APIKeyDecryptedEvent.InputTuple,
      APIKeyDecryptedEvent.OutputTuple,
      APIKeyDecryptedEvent.OutputObject
    >;
    APIKeyDecrypted: TypedContractEvent<
      APIKeyDecryptedEvent.InputTuple,
      APIKeyDecryptedEvent.OutputTuple,
      APIKeyDecryptedEvent.OutputObject
    >;

    "APIKeyEncrypted(bytes32)": TypedContractEvent<
      APIKeyEncryptedEvent.InputTuple,
      APIKeyEncryptedEvent.OutputTuple,
      APIKeyEncryptedEvent.OutputObject
    >;
    APIKeyEncrypted: TypedContractEvent<
      APIKeyEncryptedEvent.InputTuple,
      APIKeyEncryptedEvent.OutputTuple,
      APIKeyEncryptedEvent.OutputObject
    >;

    "ROFLAuthorizationCheck(address,bool)": TypedContractEvent<
      ROFLAuthorizationCheckEvent.InputTuple,
      ROFLAuthorizationCheckEvent.OutputTuple,
      ROFLAuthorizationCheckEvent.OutputObject
    >;
    ROFLAuthorizationCheck: TypedContractEvent<
      ROFLAuthorizationCheckEvent.InputTuple,
      ROFLAuthorizationCheckEvent.OutputTuple,
      ROFLAuthorizationCheckEvent.OutputObject
    >;

    "ROFLStorageAccessed(bytes32,address)": TypedContractEvent<
      ROFLStorageAccessedEvent.InputTuple,
      ROFLStorageAccessedEvent.OutputTuple,
      ROFLStorageAccessedEvent.OutputObject
    >;
    ROFLStorageAccessed: TypedContractEvent<
      ROFLStorageAccessedEvent.InputTuple,
      ROFLStorageAccessedEvent.OutputTuple,
      ROFLStorageAccessedEvent.OutputObject
    >;

    "ROFLStorageSet(bytes32,uint256)": TypedContractEvent<
      ROFLStorageSetEvent.InputTuple,
      ROFLStorageSetEvent.OutputTuple,
      ROFLStorageSetEvent.OutputObject
    >;
    ROFLStorageSet: TypedContractEvent<
      ROFLStorageSetEvent.InputTuple,
      ROFLStorageSetEvent.OutputTuple,
      ROFLStorageSetEvent.OutputObject
    >;
  };
}
