/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IERC7857DataVerifier {
  export type OwnershipProofOutputStruct = {
    dataHashes: BytesLike[];
    isValid: boolean;
  };

  export type OwnershipProofOutputStructOutput = [
    dataHashes: string[],
    isValid: boolean
  ] & { dataHashes: string[]; isValid: boolean };

  export type TransferValidityProofOutputStruct = {
    oldDataHashes: BytesLike[];
    newDataHashes: BytesLike[];
    pubKey: BytesLike;
    sealedKey: BytesLike;
    isValid: boolean;
  };

  export type TransferValidityProofOutputStructOutput = [
    oldDataHashes: string[],
    newDataHashes: string[],
    pubKey: string,
    sealedKey: string,
    isValid: boolean
  ] & {
    oldDataHashes: string[];
    newDataHashes: string[];
    pubKey: string;
    sealedKey: string;
    isValid: boolean;
  };
}

export interface OasisTEEVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "verifyOwnership" | "verifyTransferValidity"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProofVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "verifyOwnership",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTransferValidity",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTransferValidity",
    data: BytesLike
  ): Result;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [proofHash: BytesLike, isValid: boolean];
  export type OutputTuple = [proofHash: string, isValid: boolean];
  export interface OutputObject {
    proofHash: string;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OasisTEEVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): OasisTEEVerifier;
  waitForDeployment(): Promise<this>;

  interface: OasisTEEVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyOwnership: TypedContractMethod<
    [_proof: BytesLike],
    [IERC7857DataVerifier.OwnershipProofOutputStructOutput],
    "nonpayable"
  >;

  verifyTransferValidity: TypedContractMethod<
    [_proof: BytesLike],
    [IERC7857DataVerifier.TransferValidityProofOutputStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyOwnership"
  ): TypedContractMethod<
    [_proof: BytesLike],
    [IERC7857DataVerifier.OwnershipProofOutputStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyTransferValidity"
  ): TypedContractMethod<
    [_proof: BytesLike],
    [IERC7857DataVerifier.TransferValidityProofOutputStructOutput],
    "nonpayable"
  >;

  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;

  filters: {
    "ProofVerified(bytes32,bool)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
  };
}
